#!/bin/bash
# Do not use "set -e" — a failed migration or cache command must not kill the container.

PORT="${PORT:-80}"
sed -i "s/__PORT__/${PORT}/g" /etc/nginx/conf.d/symfony.conf
echo "Nginx will listen on port ${PORT}"

rm -f /app/.env.local /app/.env.local.php

export APP_ENV="${APP_ENV:-prod}"
export APP_DEBUG="${APP_DEBUG:-0}"
if [ -z "${APP_SECRET}" ]; then
    echo "WARNING: APP_SECRET is not set — set it in Railway Variables." >&2
    export APP_SECRET="unsafe-default-set-APP_SECRET-in-railway"
fi
# Empty MAILER_DSN on Railway ("") is not replaced by ${VAR:-default} — normalize explicitly.
if [ -z "${MAILER_DSN}" ] || ! echo "${MAILER_DSN}" | grep -qE '^[a-zA-Z0-9.+_-]+://'; then
    if [ -n "${MAILER_DSN}" ]; then
        echo "WARNING: MAILER_DSN is invalid — using null://null. Set a full DSN (e.g. smtp://user:pass@host:587)." >&2
    fi
    export MAILER_DSN="null://null"
fi
export MAILER_FROM_ADDRESS="${MAILER_FROM_ADDRESS:-noreply@localhost}"
export MAILER_FROM_NAME="${MAILER_FROM_NAME:-Shoes R Us}"
export MESSENGER_TRANSPORT_DSN="${MESSENGER_TRANSPORT_DSN:-sync://}"
export CORS_ALLOW_ORIGIN="${CORS_ALLOW_ORIGIN:-^.*$}"
export JWT_PASSPHRASE="${JWT_PASSPHRASE:-}"

mkdir -p /app/config/jwt
if [ ! -f /app/config/jwt/private.pem ]; then
    openssl genpkey -algorithm RSA -out /app/config/jwt/private.pem -pkeyopt rsa_keygen_bits:4096
    openssl pkey -in /app/config/jwt/private.pem -pubout -out /app/config/jwt/public.pem
    chmod 600 /app/config/jwt/private.pem
    chmod 644 /app/config/jwt/public.pem
    export JWT_PASSPHRASE=""
    echo "Generated JWT keys (no passphrase)."
elif [ -n "${JWT_PASSPHRASE}" ] && ! openssl pkey -in /app/config/jwt/private.pem -passin "pass:${JWT_PASSPHRASE}" -noout 2>/dev/null; then
    echo "WARNING: JWT_PASSPHRASE does not match private.pem — clearing it (Docker keys are unencrypted)." >&2
    export JWT_PASSPHRASE=""
fi
# PHP-FPM runs as www-data; keys are created root:root mode 600 during build/entrypoint.
chown www-data:www-data /app/config/jwt/private.pem /app/config/jwt/public.pem 2>/dev/null || true
if [ -z "${DEFAULT_URI}" ] && [ -n "${RAILWAY_PUBLIC_DOMAIN}" ]; then
    export DEFAULT_URI="https://${RAILWAY_PUBLIC_DOMAIN}"
fi
export DEFAULT_URI="${DEFAULT_URI:-http://localhost}"
export APP_ROOT_TO_ADMIN="${APP_ROOT_TO_ADMIN:-0}"

export GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID:-}"
export GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET:-}"
export GOOGLE_ANDROID_CLIENT_ID="${GOOGLE_ANDROID_CLIENT_ID:-}"
export GOOGLE_IOS_CLIENT_ID="${GOOGLE_IOS_CLIENT_ID:-}"
export APP_DEEP_LINK_SCHEME="${APP_DEEP_LINK_SCHEME:-vallejera}"
if [ -z "${GOOGLE_CALLBACK_URL}" ] && [ -n "${DEFAULT_URI}" ]; then
    export GOOGLE_CALLBACK_URL="${DEFAULT_URI}/connect/google/check"
fi
if [ -z "${GOOGLE_CLIENT_ID}" ] || [ -z "${GOOGLE_CLIENT_SECRET}" ]; then
    echo "WARNING: GOOGLE_CLIENT_ID or GOOGLE_CLIENT_SECRET is missing — Google login will not work." >&2
    echo "  Set both on the Railway *app* service (exact names), then redeploy." >&2
else
    echo "Google OAuth: client ID present (${#GOOGLE_CLIENT_ID} characters)."
fi

configure_php_fpm_env() {
    local fpm_conf="/usr/local/etc/php-fpm.d/zz-srusystem-env.conf"
    {
        echo "; Generated by entrypoint — expose container env to PHP-FPM (clear_env defaults to yes)"
        echo "clear_env = no"
        for var in APP_ENV APP_DEBUG APP_SECRET DATABASE_URL MAILER_DSN MAILER_FROM_ADDRESS \
            GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET GOOGLE_CALLBACK_URL \
            GOOGLE_ANDROID_CLIENT_ID GOOGLE_IOS_CLIENT_ID DEFAULT_URI APP_DEEP_LINK_SCHEME \
            APP_ROOT_TO_ADMIN CORS_ALLOW_ORIGIN JWT_PASSPHRASE; do
            val="${!var:-}"
            if [ -n "$val" ]; then
                printf 'env[%s] = "%s"\n' "$var" "$(quote_env "$val")"
            fi
        done
    } > "${fpm_conf}"
}

# Build DATABASE_URL from Railway MySQL (many variable naming conventions).
resolve_database_url() {
    if [ -n "${MYSQL_URL}" ]; then
        export DATABASE_URL="${MYSQL_URL}"
        return 0
    fi
    if [ -n "${MYSQL_PRIVATE_URL}" ]; then
        export DATABASE_URL="${MYSQL_PRIVATE_URL}"
        return 0
    fi
    if [ -n "${DATABASE_URL}" ] && ! echo "${DATABASE_URL}" | grep -qE '@(127\.0\.0\.1|localhost)([:/]|$)'; then
        return 0
    fi
    local host="${MYSQLHOST:-${MYSQL_HOST:-${PGHOST:-}}}"
    local port="${MYSQLPORT:-${MYSQL_PORT:-${PGPORT:-3306}}}"
    local user="${MYSQLUSER:-${MYSQL_USER:-${PGUSER:-}}}"
    local pass="${MYSQLPASSWORD:-${MYSQL_PASSWORD:-${PGPASSWORD:-}}}"
    local db="${MYSQLDATABASE:-${MYSQL_DATABASE:-${PGDATABASE:-}}}"
    if [ -n "${host}" ] && [ -n "${user}" ] && [ -n "${db}" ]; then
        local enc_user enc_pass
        enc_user=$(php -r 'echo rawurlencode($argv[1]);' "${user}")
        enc_pass=$(php -r 'echo rawurlencode($argv[1]);' "${pass}")
        export DATABASE_URL="mysql://${enc_user}:${enc_pass}@${host}:${port}/${db}"
        echo "Built DATABASE_URL from Railway MySQL variables (host=${host})."
        return 0
    fi
    if echo "${DATABASE_URL:-}" | grep -qE '@(127\.0\.0\.1|localhost)([:/]|$)'; then
        echo "ERROR: DATABASE_URL points to localhost — link the MySQL service on Railway." >&2
        unset DATABASE_URL
    fi
    return 1
}

resolve_database_url || true

if [ -n "${DATABASE_URL}" ] && ! echo "${DATABASE_URL}" | grep -q 'serverVersion='; then
    if echo "${DATABASE_URL}" | grep -q '?'; then
        export DATABASE_URL="${DATABASE_URL}&serverVersion=8.0.32&charset=utf8mb4"
    else
        export DATABASE_URL="${DATABASE_URL}?serverVersion=8.0.32&charset=utf8mb4"
    fi
fi

if echo "${APP_SECRET}" | grep -q '[[:space:]]'; then
    echo "ERROR: APP_SECRET must be one random string with NO spaces or comments." >&2
fi

quote_env() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}
{
    echo "APP_ENV=${APP_ENV}"
    echo "APP_DEBUG=${APP_DEBUG}"
    echo "APP_SECRET=\"$(quote_env "${APP_SECRET}")\""
    echo "APP_ROOT_TO_ADMIN=${APP_ROOT_TO_ADMIN}"
    [ -n "${DATABASE_URL}" ] && echo "DATABASE_URL=\"$(quote_env "${DATABASE_URL}")\""
    echo "MAILER_DSN=\"$(quote_env "${MAILER_DSN}")\""
    echo "MAILER_FROM_ADDRESS=\"$(quote_env "${MAILER_FROM_ADDRESS}")\""
    echo "MAILER_FROM_NAME=\"$(quote_env "${MAILER_FROM_NAME}")\""
    echo "MESSENGER_TRANSPORT_DSN=\"$(quote_env "${MESSENGER_TRANSPORT_DSN}")\""
    echo "CORS_ALLOW_ORIGIN=\"$(quote_env "${CORS_ALLOW_ORIGIN}")\""
    echo "DEFAULT_URI=\"$(quote_env "${DEFAULT_URI}")\""
    echo "JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem"
    echo "JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem"
    echo "JWT_PASSPHRASE=\"$(quote_env "${JWT_PASSPHRASE}")\""
    echo "GOOGLE_CLIENT_ID=\"$(quote_env "${GOOGLE_CLIENT_ID}")\""
    echo "GOOGLE_CLIENT_SECRET=\"$(quote_env "${GOOGLE_CLIENT_SECRET}")\""
    echo "GOOGLE_CALLBACK_URL=\"$(quote_env "${GOOGLE_CALLBACK_URL:-}")\""
    echo "GOOGLE_ANDROID_CLIENT_ID=\"$(quote_env "${GOOGLE_ANDROID_CLIENT_ID}")\""
    echo "GOOGLE_IOS_CLIENT_ID=\"$(quote_env "${GOOGLE_IOS_CLIENT_ID}")\""
    echo "APP_DEEP_LINK_SCHEME=\"$(quote_env "${APP_DEEP_LINK_SCHEME}")\""
} > /app/.env
echo "Symfony .env file rebuilt for production."
if echo "${MAILER_DSN}" | grep -qE '^null://'; then
    echo "WARNING: MAILER_DSN is null://null — verification emails will NOT be delivered. Set MAILER_DSN (SMTP) in Railway Variables." >&2
fi

if [ -n "${DATABASE_URL}" ]; then
    echo "Database target: $(php -r 'echo parse_url($argv[1], PHP_URL_HOST) ?: "unknown";' "${DATABASE_URL}")"
else
    echo "WARNING: DATABASE_URL is not set — link MySQL to this service on Railway." >&2
fi

run_console() {
    php bin/console "$@" --env="${APP_ENV}" --no-debug
}

echo "Clearing Symfony cache..."
run_console cache:clear || echo "WARNING: cache:clear failed — continuing." >&2

echo "Warming up Symfony cache..."
run_console cache:warmup || run_console cache:clear || true

mkdir -p var/sessions
chown -R www-data:www-data var/cache var/log var/sessions 2>/dev/null || true
chmod -R 775 var/cache var/log var/sessions 2>/dev/null || true

# PHP CLI often cannot read DATABASE_URL via getenv() (variables_order); pass URL as argv[1].
test_db_connection() {
    php -r '
$url = $argv[1] ?? "";
if ($url === "") {
    fwrite(STDERR, "missing database url argument");
    exit(2);
}
$p = parse_url($url);
if ($p === false || empty($p["host"])) {
    fwrite(STDERR, "invalid database url");
    exit(2);
}
$host = $p["host"];
$port = $p["port"] ?? 3306;
$user = $p["user"] ?? null;
$pass = $p["pass"] ?? null;
$dsn = "mysql:host={$host};port={$port};charset=utf8mb4";
try {
    $pdo = new PDO($dsn, $user, $pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_TIMEOUT => 5,
    ]);
    $pdo->query("SELECT 1");
    echo "ok";
} catch (Throwable $e) {
    fwrite(STDERR, $e->getMessage());
    exit(1);
}
' "$DATABASE_URL"
}

wait_for_db() {
    if [ -z "${DATABASE_URL}" ]; then
        return 1
    fi
    echo "Waiting for database to become available..."
    retries=8
    delay=2
    while [ $retries -gt 0 ]; do
        err=$(test_db_connection 2>&1) && rc=0 || rc=$?
        if [ "$rc" -eq 0 ]; then
            echo "Database ready"
            return 0
        fi
        if [ -n "${err}" ]; then
            echo "DB not ready yet (exit ${rc}): ${err} — sleeping ${delay}s..."
        else
            echo "DB not ready yet (exit ${rc}) — sleeping ${delay}s..."
        fi
        retries=$((retries-1))
        sleep $delay
    done
    echo "Timed out waiting for database." >&2
    return 1
}

run_post_deploy_tasks() {
    if [ -z "${DATABASE_URL}" ]; then
        echo "WARNING: DATABASE_URL is not set — skipping migrations and seed." >&2
        return 0
    fi
    if ! wait_for_db; then
        echo "WARNING: database unreachable — skipping migrations (app will still run)." >&2
        return 0
    fi

    echo "Running database migrations..."
    run_console doctrine:migrations:sync-metadata-storage --no-interaction 2>/dev/null || true
    if ! run_console doctrine:migrations:migrate --no-interaction --allow-no-migration; then
        echo "WARNING: migrations failed — retrying once." >&2
        sleep 3
        run_console doctrine:migrations:migrate --no-interaction --allow-no-migration || true
    fi

    run_console app:verify-staff-for-login --no-interaction || true

    bootstrap_email="${BOOTSTRAP_ADMIN_EMAIL:-}"
    bootstrap_password="${BOOTSTRAP_ADMIN_PASSWORD:-}"
    if [ "${ENSURE_DEFAULT_ADMIN:-0}" = "1" ]; then
        bootstrap_email="${bootstrap_email:-admin@shoesrus.local}"
    fi
    if [ -n "${bootstrap_email}" ] && [ -n "${bootstrap_password}" ]; then
        echo "Ensuring admin login account (${bootstrap_email})..."
        run_console app:create-admin \
            --email="${bootstrap_email}" \
            --password="${bootstrap_password}" \
            --full-name="System Admin" \
            --no-interaction || true
    fi

    bootstrap_staff_email="${BOOTSTRAP_STAFF_EMAIL:-}"
    bootstrap_staff_password="${BOOTSTRAP_STAFF_PASSWORD:-}"
    if [ "${ENSURE_DEFAULT_STAFF:-0}" = "1" ]; then
        bootstrap_staff_email="${bootstrap_staff_email:-staff@shoesrus.local}"
    fi
    if [ -n "${bootstrap_staff_email}" ] && [ -n "${bootstrap_staff_password}" ]; then
        echo "Ensuring staff login account (${bootstrap_staff_email})..."
        run_console app:create-staff \
            --email="${bootstrap_staff_email}" \
            --password="${bootstrap_staff_password}" \
            --full-name="Demo Staff" \
            --no-interaction || true
    fi

    import_file="${DATABASE_IMPORT_FILE:-/app/data/railway-import.sql}"
    if [ -f "${import_file}" ]; then
        run_console app:import-mysql-dump "${import_file}" --only-if-empty --no-interaction || true
    fi

    if [ "${LOAD_APP_FIXTURES:-0}" = "1" ]; then
        echo "WARNING: LOAD_APP_FIXTURES=1 purges products, orders, and users on every deploy — unset after first load." >&2
        echo "Loading application fixtures (FixtureLoader)..."
        run_console app:load-fixtures --no-interaction || true
    else
        run_console app:seed-demo-products --no-interaction || true
    fi
}

# Start web stack first so Railway health checks pass, then run DB tasks in background.
configure_php_fpm_env
echo "Starting PHP-FPM..."
php-fpm -D

echo "Starting Nginx (migrations run in background)..."
run_post_deploy_tasks &
exec nginx -g "daemon off;"
